---
- hosts: all
  become: true
  tasks:
  - name: Install Apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install httpd & php for CentOS
    yum:
      name: 
        - epel-release
        - httpd
        - php
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS'