---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo (CentOS)
      tags: always
      yum:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == 'CentOS'  
      
    - name: update repo  (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  gather_facts: false
  become: true
  roles:
    - web_servers
  
- hosts: db_servers
  become: true
  gather_facts: false
  roles:
    - db_servers

- hosts: file_servers
  gather_facts: false
  become: yes
  roles:
    - file_servers